sudo: required
addons:
  apt:
    packages:
      - libseccomp-dev
before_install:
- sudo add-apt-repository 'deb https://raw.githubusercontent.com/godarch/debian-repo/master/darch testing main'
- sudo apt-get update
- sudo apt-get install darch
- sudo systemctl start containerd
- darch version
- sudo ctr version
- sudo runc --version
- sudo darch images pull godarch/ubuntu:cosmic
script:
- "./ci"
